set-environment -g PATH "$HOME/.local/bin:$PATH"

# Bỏ prefix mặc định
unbind C-b

# Đặt prefix mới là Ctrl-Space
set -g prefix C-Space
bind C-Space send-prefix

# Di chuyển giữa các pane theo phong cách vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize pane với Prefix + H/J/K/L (chữ hoa, giữ Shift)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fabioluciano/tmux-powerkit'

# Basic configuration
set -g @powerkit_plugins "datetime,battery,cpu,memory,git,hostname"
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "mocha"
# set -g @powerkit_separator_style "rounded"
# set -g @powerkit_elements_spacing "both"

set -g status-position top

setw -g mode-keys vi

run '~/.tmux/plugins/tpm/tpm'
